INSERT INTO quiz_category (category_name) VALUES ('Arts And Literature');
INSERT INTO quiz_category (category_name) VALUES ('Film And Tv');
INSERT INTO quiz_category (category_name) VALUES ('Food And Drink');
INSERT INTO quiz_category (category_name) VALUES ('General Knowledge');
INSERT INTO quiz_category (category_name) VALUES ('Geography');
INSERT INTO quiz_category (category_name) VALUES ('History');
INSERT INTO quiz_category (category_name) VALUES ('Music');
INSERT INTO quiz_category (category_name) VALUES ('Science');
INSERT INTO quiz_category (category_name) VALUES ('Society And Culture');
INSERT INTO quiz_category (category_name) VALUES ('Sport And Leisure');
